<a href="https://colab.research.google.com/github/Shreyes45/ML-LAB/blob/main/Lab6-deccisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Decision Tree for IRIS and Drug datasets

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor
from sklearn.metrics import accuracy_score, confusion_matrix,mean_absolute_error,mean_squared_error
from sklearn.preprocessing import LabelEncoder

# IRIS
iris = pd.read_csv("iris.csv")
X = iris.drop("species", axis=1)
y = iris["species"]
Xtr,Xte,ytr,yte = train_test_split(X,y,test_size=0.2,random_state=42)
model = DecisionTreeClassifier().fit(Xtr,ytr)
pred = model.predict(Xte)
print("IRIS Accuracy:",accuracy_score(yte,pred))
print(confusion_matrix(yte,pred))

# DRUG
drug = pd.read_csv("drug.csv")
le = LabelEncoder()
for c in drug.columns:
    drug[c] = le.fit_transform(drug[c])

X = drug.drop("Drug",axis=1)
y = drug["Drug"]
Xtr,Xte,ytr,yte = train_test_split(X,y,test_size=0.2,random_state=42)
model = DecisionTreeClassifier().fit(Xtr,ytr)
pred = model.predict(Xte)
print("\nDrug Accuracy:",accuracy_score(yte,pred))
print(confusion_matrix(yte,pred))


petrol = pd.read_csv("petrol_consumption.csv")
X = petrol.drop("Petrol_Consumption",axis=1)
y = petrol["Petrol_Consumption"]
Xtr,Xte,ytr,yte = train_test_split(X,y,test_size=0.2,random_state=42)
model = DecisionTreeRegressor().fit(Xtr,ytr)
p = model.predict(Xte)

print("\nPetrol Dataset Errors")
print("MAE:",mean_absolute_error(yte,p))
print("MSE:",mean_squared_error(yte,p))
print("RMSE:",np.sqrt(mean_squared_error(yte,p)))

IRIS Accuracy: 1.0
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Drug Accuracy: 1.0
[[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]

Petrol Dataset Errors
MAE: 83.6
MSE: 15451.4
RMSE: 124.30366044489598


In [8]:
petrol = pd.read_csv("petrol_consumption.csv")
X = petrol.drop("Petrol_Consumption",axis=1)
y = petrol["Petrol_Consumption"]
Xtr,Xte,ytr,yte = train_test_split(X,y,test_size=0.2,random_state=42)
model = DecisionTreeRegressor().fit(Xtr,ytr)
p = model.predict(Xte)

print("\nPetrol Dataset Errors")
print("MAE:",mean_absolute_error(yte,p))
print("MSE:",mean_squared_error(yte,p))
print("RMSE:",np.sqrt(mean_squared_error(yte,p)))


Petrol Dataset Errors
MAE: 96.9
MSE: 17661.3
RMSE: 132.8958238621515
